# Generated by Django 4.0.5 on 2022-07-01 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=30, verbose_name='Nombre de la Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('idEspecie', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la especie')),
                ('nombreEspecie', models.CharField(max_length=30, verbose_name='Nombre de la especie')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('idArticulo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='numero de producto')),
                ('precio', models.IntegerField(max_length=50, verbose_name='Precio ')),
                ('nombreProducto', models.CharField(max_length=30, verbose_name='Nombre')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.categoria')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.especie')),
            ],
        ),
    ]
