# Generated by Django 4.0.5 on 2022-06-28 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=30, verbose_name='Nombre de la Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('idArticulo', models.IntegerField(max_length=5, primary_key=True, serialize=False, verbose_name='numero de producto')),
                ('Precio', models.IntegerField(max_length=50, verbose_name='Precio ')),
                ('especie', models.CharField(blank=True, max_length=20, null=True, verbose_name='especie')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.categoria')),
            ],
        ),
    ]
