# Generated by Django 4.0.5 on 2022-07-01 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='especie',
            fields=[
                ('idEspecie', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la especie')),
                ('nombreEspecie', models.CharField(max_length=30, verbose_name='Nombre de la especie')),
            ],
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='categoria',
            new_name='Categoria',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.especie'),
        ),
    ]
